services:
  app:
    image: binarfud
    build:
      context: .
    ports:
      - "9080:8080"
    environment:
      - BINARFUD_DB_HOST=
      - BINARFUD_DB_PORT=
      - BINARFUD_DB_NAME=
      - BINARFUD_DB_USERNAME=
      - BINARFUD_DB_PASSWORD=
      - BINARFUD_JWT_SECRET_KEY=
      - BINARFUD_JWT_EXPIRATION_TIME=
      - BINARFUD_JWT_REFRESH_TOKEN_SECRET_KEY=
      - BINARFUD_JWT_REFRESH_TOKEN_EXPIRATION_TIME=
      - BINARFUD_OAUTH2_GOOGLE_CLIENT_ID=
      - BINARFUD_OAUTH2_GOOGLE_CLIENT_SECRET=
      - BINARFUD_MAIL_HOST=
      - BINARFUD_MAIL_PORT=
      - BINARFUD_MAIL_USERNAME=
      - BINARFUD_MAIL_PASSWORD=
